[package]
name = "ownership"
type = "bin"
authors = [""]
compiler_version = ">=0.30.0"

[dependencies]
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }
sha256 = { git = "https://github.com/noir-lang/sha256", tag = "v0.2.1" }
